#++++++++++++++++++++++++++++++++++++++
# mongo Docker container
#++++++++++++++++++++++++++++++++++++++
#
# Official images:
#
#   mongo - official mongo
#           https://hub.docker.com/_/mongo
#
#++++++++++++++++++++++++++++++++++++++

FROM mongo:latest


